export const LOGIN = '/login'
export const REGISTER = '/register'
export const MARKET = '/market'
export const COLLECTIONS = '/collections'
export const EXPLORE = '/'
export const NEWS = '/news'
export const PORTFOLIO = '/portfolio'
export const DETAILS = '/details/:stockSymbol'