export const LOGIN = '/login'
export const REGISTER = '/register'
export const EVENTS = '/events'
export const COMPARE = '/compare'
export const EXPLORE = '/'
export const NEWS = '/news'
export const PORTFOLIO = '/portfolio'
export const DETAILS = '/details/:stockSymbol'